### PR TITLE
WIP: Initialize Blackbox

### PR DESCRIPTION
**Pull request by oxr463**
- [x] Find and add contributor keys (See: https://www.gentoo.org/inside-gentoo/developers).
- [ ] Create override configs for Docker Compose (See: https://docs.docker.com/compose/extends/#multiple-compose-files)
- [ ] Encrypt override configs
- [ ] Add documentation to README.md

Bug: https://github.com/aliceinwire/GkernelCI_docker/issues/1

### CODE REVIEW

**Comment by aliceinwire** [comment]
any progress on this ?

**Comment by oxr463** [comment]
How do Gentoo developers keep track of their secrets for shared infrastructure now?

**Comment by aliceinwire** [comment]
I think we should not mind about the gpg to use as that will be maybe optional. just having  the implementation should be enough.

**Comment by oxr463** [comment]
> I think we should not mind about the gpg to use as that will be maybe optional. just having the implementation should be enough.
> git should use the gpg when is doing a commit to any Gentoo git repository.

So how blackbox works is, we encrypt the secrets before committing them to the repository. Then anyone listed as an admin, can use their GPG key to access the secrets. So for example, you are the admin, so we add your key. Then if you granted me or someone else access, they could unencrypt the secrets.

**Comment by aliceinwire** [comment]
@mjeveritt can you add copy your public key here? so that lucas will add it to blackbox ?

**Comment by aliceinwire** [comment]
tested and works correctly

**Comment by aliceinwire** [comment]
merging this

**Pull request merged**
